name: Deploy-Process
on:
  push:
    branches: 
      - main
    #tags:
    #- release-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.13.1
        cache: 'npm'
    
    - name: npm install, build
      run: |
        npm install
        ls -la
        npm run build --if-present
